# Generated by Django 4.1.2 on 2022-10-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_user_department_alter_department_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='software', max_length=50),
            preserve_default=False,
        ),
    ]
