# Generated by Django 4.1.2 on 2022-11-01 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0005_user_created_at_user_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_model',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
